/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab_04;

import org.junit.Test;

import java.awt.image.BufferedImage;

import static org.junit.Assert.*;

public class AppTest {
}
